services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  app:
    # CORRECCIÓN: Le decimos que use el Dockerfile que está en la misma carpeta
    build: .
    container_name: miturno_app
    ports:
      - "8505:8505"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONUNBUFFERED=1
    # CORRECCIÓN: Hemos eliminado el 'volumes: - .:/app' y el 'command' gigante.
    # Tu Dockerfile ya se encarga de tener los archivos listos y ejecutar Streamlit.
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
